version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Test
          command: ./hello

      - run:
          name: Package
          command: tar --exclude='./.git' --exclude='./README.md' --exclude="hello.tar.gz" --exclude='./.circleci' -zcvf "hello.tar.gz" .

      - run:
          name: Release
          command: ./release.sh
