version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Test
          command: ./hello

      - run:
          name: Prerequisites
          command: sudo apt-get -y update && sudo apt-get -y install git python curl

      - run:
          name: Release
          command: ./release.sh
