version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Test
          command: ./hello

      - run:
          name: Release
          command: ./release.sh
